services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"

# services:
#   sql:
#     image: mcr.microsoft.com/azure-sql-edge
#     container_name: sql
#     environment:
#       ACCEPT_EULA: "1"
#       MSSQL_SA_PASSWORD: "Password@1"
#     ports:
#       - "1433:1433"   